name: achitecture_weup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #a

  #c
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1

  #d
  dotted_decoration: ^2.0.0
  #e
  easy_localization:
    git: https://github.com/manhtai831/easy_localization

  #f
  flutter_svg: ^0.23.0
  flutter_local_notifications: ^9.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_scroll_to_top: ^2.1.1
  firebase_messaging: ^11.2.4
  firebase_core: ^1.10.6
  flex_color_scheme: ^5.0.0
  flutter_html: ^2.1.5
  fluttertoast: ^8.0.9

  #h
  hive: ^2.1.0

  #i
  intl: ^0.17.0
  image_picker: ^0.8.5
  image_cropper: ^2.0.2
  #o
  overflow_view: ^0.3.1

  #p
  pull_to_refresh: ^2.0.0
  provider: ^6.0.0
  path_provider: ^2.0.9
  permission_handler: ^8.3.0
  photo_view: ^0.13.0

  #r
  retrofit: 3.0.1

  #s
  syncfusion_flutter_datepicker: ^20.1.50
  share_plus: ^4.0.4
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0

  #u
  url_launcher: ^6.0.20

  #w
  wechat_assets_picker: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  pretty_dio_logger: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/translations/

#  fonts:
#    - family: Babylon
#      fonts:
#        - asset: assets/fonts/baloo_bhai2_bold.ttf
#          weight: 900
#        - asset: assets/fonts/baloo_bhai2_medium.ttf
#          weight: 600
#        - asset: assets/fonts/baloo_bhai2_regular.ttf
#          weight: 400
#  flutter_icons:
#    android: true
#    ios: true
#    image_path: "assets/icons/launcher_icon.png"
  #  Change icon:
  #  - flutter pub get
  #  - flutter pub run flutter_launcher_icons:main
