name: achitecture_weup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  domain:
    path: ./domain
  data:
    path: ./data
  translator:
    path: ./dependencies/translator
  storage:
    path: ./dependencies/storage
  extensions:
    path: ./dependencies/extensions
  state:
    path: ./dependencies/state
  widgets:
    path: ./dependencies/widgets
  image_picker_utils:
    path: ./dependencies/image_picker_utils
  firebase_manager:
    path: ./dependencies/firebase_manager
  permission_config:
    path: ./dependencies/permission_config

  #c
  cupertino_icons: ^1.0.2




  fluttertoast: ^8.0.9

  #p
  provider: ^6.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/translations/

  #  fonts:
  #    - family: Babylon
  #      fonts:
  #        - asset: assets/fonts/baloo_bhai2_bold.ttf
  #          weight: 900
  #        - asset: assets/fonts/baloo_bhai2_medium.ttf
  #          weight: 600
  #        - asset: assets/fonts/baloo_bhai2_regular.ttf
  #          weight: 400
  #  flutter_icons:
  #    android: true
  #    ios: true
  #    image_path: "assets/icons/launcher_icon.png"
  #  Change icon:
  #  - flutter pub get
  #  - flutter pub run flutter_launcher_icons:main
