name: widgets
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:

  flutter:
    sdk: flutter

  translator:
    path: ../translator
  extensions:
    path: ../extensions
  permission_config:
    path: ../permission_config
  image_picker_utils:
    path: ../image_picker_utils

  image_picker: ^0.8.5

  permission_handler: ^8.3.0
  pull_to_refresh: ^2.0.0

  syncfusion_flutter_datepicker: 20.1.50
  syncfusion_flutter_pdfviewer: ^20.1.52-beta
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0

  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1

  flutter_svg: ^0.23.0
  flutter_html: ^2.1.5
  flutter_map: ^0.14.0

  dotted_decoration: ^2.0.0
  latlong2: ^0.8.1

  overflow_view: ^0.3.1

  wechat_assets_picker: ^7.2.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
