// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzV25s9rO-Qt7wPnJbRTascKziDC6iE4',
    appId: '1:685865949683:web:2a04e9c797cf008924da86',
    messagingSenderId: '685865949683',
    projectId: 'weup-a6598',
    authDomain: 'weup-a6598.firebaseapp.com',
    storageBucket: 'weup-a6598.appspot.com',
    measurementId: 'G-KG6PKRNLL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvUqFjIfjAdHWCcmIJbKA_0HQrXxe-Vl4',
    appId: '1:685865949683:android:b2ac74d9b46d497724da86',
    messagingSenderId: '685865949683',
    projectId: 'weup-a6598',
    storageBucket: 'weup-a6598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKdKl18nl_SYEp594ihRK6jMg5EIgW20',
    appId: '1:685865949683:ios:93b15fb5793a811124da86',
    messagingSenderId: '685865949683',
    projectId: 'weup-a6598',
    storageBucket: 'weup-a6598.appspot.com',
    iosClientId: '685865949683-chi9e1qhmdgbcsa4jgpgeuncidk360gn.apps.googleusercontent.com',
    iosBundleId: 'vn.weupgroup.achitechweup.achitechWeup',
  );
}
