name: image_picker_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:

  flutter:
    sdk: flutter

  translator:
    path: ../translator
  permission_config:
    path: ../permission_config

  image_cropper: ^2.0.2
  image_picker: ^0.8.5
  flutter_image_compress: ^1.1.1
  path_provider: ^2.0.11
  video_compress: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
