name: permission_config
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:

  flutter:
    sdk: flutter

  extensions:
    path: ../extensions
  translator:
    path: ../translator

  permission_handler: ^8.3.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
